"""Globally used constants
"""

PERSONA_YOU = 'You'
PERSONA_ASSISTANT = 'assistant'
PERSONA_SYSTEM = 'system'
PERSONA_SPEAKER = 'Speaker'

LOG_NAME = 'Transcribe'
MAX_TRANSCRIPTION_PHRASES_FOR_LLM = 20
TRANSCRIPT_UI_UPDATE_DELAY_DURATION_MS = 500
